### ISSUE TITLE
maker_faire_hat_2_simulator code is missing

### ISSUE THREAD

**Issue by JackZielke** [JohnPetersen/Seeker_Hats#1]
Any chance we can have access to the simulator for testing?

Thanks!!

**Comment by JohnPetersen** [comment]
Absolutely. It's going to take me 12 to 24 hours to post it.

**Comment by JohnPetersen** [comment]
The simulator code has been pushed to this repository: https://github.com/JohnPetersen/Seeker_Hat_Simulator

**Comment by JackZielke** [comment]
Thank you so much!!
